package cn.javass.test;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowCallbackHandler;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

public class JdbcTemplateTest
{
	private static JdbcTemplate jdbcTemplate;

	@BeforeClass
	public static void setUpClass()
	{
		String url = "jdbc:hsqldb:mem:test";
		String username = "sa";
		String password = "";
		DriverManagerDataSource dataSource = new DriverManagerDataSource(url, username, password);
		dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
		jdbcTemplate = new JdbcTemplate(dataSource);
	}

	@Test
	public void test()
	{
		// 1.声明SQL
		String sql = "select * from INFORMATION_SCHEMA.SYSTEM_TABLES";
		jdbcTemplate.query(sql, new RowCallbackHandler()
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException
			{
				// 2.处理结果集
				String value = rs.getString("TABLE_NAME");
				System.out.println("Column TABLENAME:" + value);
			}
		});
	}

	// 代码片段(cn.javass.spring.chapter7.JdbcTemplateTest)
	@Before
	public void setUp()
	{
		String createTableSql = "create memory table test" + "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + "name varchar(100))";
		jdbcTemplate.update(createTableSql);
	}

	@After
	public void tearDown()
	{
		String dropTableSql = "drop table test";
		jdbcTemplate.execute(dropTableSql);
	}

	private void insert()
	{
		jdbcTemplate.update("insert into test(name) values('name1')");
		jdbcTemplate.update("insert into test(name) values('name2')");
		Assert.assertEquals(2, jdbcTemplate.queryForInt("select count(*) from test"));
	}

	private void delete()
	{
		jdbcTemplate.update("delete from test where name=?", new Object[] { "name2" });
		Assert.assertEquals(1, jdbcTemplate.queryForInt("select count(*) from test"));
	}

	private void update()
	{
		jdbcTemplate.update("update test set name='name3' where name=?", new Object[] { "name1" });
		Assert.assertEquals(1, jdbcTemplate.queryForInt("select count(*) from test where name='name3'"));
	}

	private void select()
	{
		jdbcTemplate.query("select * from test", new RowCallbackHandler()
		{
			@Override
			public void processRow(ResultSet rs) throws SQLException
			{
				System.out.print("====id:" + rs.getInt("id"));
				System.out.println(",name:" + rs.getString("name"));
			}
		});
	}
}
